from arbolBB import arbolBB

if __name__ == '__main__':
    arbol = arbolBB()
    arbol.insertar(9)
    arbol.insertar(4)
    arbol.insertar(10)
    arbol.insertar(2)
    arbol.insertar(15)
    arbol.insertar(5)
    arbol.insertar(20)
    print("Buscar", arbol.buscar(7))
    print("Buscar", arbol.buscar(20))
    arbol.InOrden()
    print(arbol.nivel(9))
    print(arbol.nivel(15))
    print(arbol.hoja(4))
    print(arbol.hoja(5))
    print(arbol.altura())
    print("4 padre de 2:", arbol.padre(4,2))
    print("10 padre de 5:", arbol.padre(10,5))
    print("2 hijo de 4:", arbol.hijo(2,4))
    print("5 hijo de 10:", arbol.hijo(5,10))
